### ISSUE TITLE
Error observed in using FreeRTOS: undefined reference to xTaskCreate()

### ISSUE THREAD

**Issue by vincentabraham** [platformio/platform-chipsalliance#4]
I’m using PlatformIO to run a FreeRTOS code on the Nexys RISC-V framework. Shown below is the platformio.ini file:

```ini
[env:swervolf_nexys]
platform = chipsalliance
board = swervolf_nexys
framework = wd-riscv-sdk, freertos
debug_tool = whisper
```

Here’s my program:
```c
#include "FreeRTOS.h"
#include "task.h"
#include <bsp_printf.h>
#include <bsp_mem_map.h>
#include <bsp_version.h>

void vTask1(void *pvParameters);
void vTask2(void *pvParameters);

int main(void)
{
    xTaskCreate(&vTask1, "Task 1", 1024, NULL, 1, NULL);
    xTaskCreate(&vTask2, "Task 2", 1024, NULL, 1, NULL);
    vTaskStartScheduler();
    return 0;
}

void vTask1(void *pvParameters)
{
    for (;;)
    {
        printfNexys("Task 1\r\n");
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
    vTaskDelete(NULL);
}

void vTask2(void *pvParameters)

{
    for (;;)
    {
        printfNexys("Task 2\r\n");
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
    vTaskDelete(NULL);
}
```
I’m getting the below error:
task_code.c:14: undefined reference to `xTaskCreate’

On running the demo provided in this repository, it seemed to run fine. However, when I tried to compile my own code, this error was observed. Please help me resolve this issue.

**Comment by valeros** [comment]
Hi @vincentabraham ! The current RTOSAL layer is configured to use statically allocated RAM, so you need to use `xTaskCreateStatic` instead.

**Comment by vincentabraham** [comment]
Actually I'm new to FreeRTOS and am still learning. Could you suggest the
changes I could make to the code for including xCreateStatic() ?  I saw
that the arguments are different for that function.

**Comment by valeros** [comment]
There is an example in the official FreeRTOS documentation https://www.freertos.org/xTaskCreateStatic.html
