### ISSUE TITLE
Error in Debugging the Nexys A7 50T

### ISSUE THREAD

**Issue by vincentabraham** [platformio/platform-chipsalliance#5]
I’m trying to debug a program Factorial.c on the Nexys A7 50T FPGA board using PlatformIO.
I have procured its bitstream file from the below GitHub repository:
https://github.com/Digilent/Nexys-A7-50T-OOB/releases/tag/v2018.2-1 
(It's in the vivado_proj\Nexys-A7-50T-OOB.runs\impl_1 directory of the ZIP file)

Shown below is the platformio.ini code:

[env:swervolf_nexys]
platform = chipsalliance
board = swervolf_nexys
framework = wd-riscv-sdk
monitor_speed = 115200

board_build.bitstream_file = D:\STUDIES\NexysFiles\Nexys-A7-50T-OOB-2018.2-1\vivado_proj\Nexys-A7-50T-OOB.runs\impl_1\nexys50t.bit

Shown below is the program code:

#if defined(D_NEXYS_A7)
   #include <bsp_printf.h>
   #include <bsp_mem_map.h>
   #include <bsp_version.h>
#else
   PRE_COMPILED_MSG("no platform was defined")
#endif
#include <psp_api.h>
#define N 7

int main(void)
{  
    int fact = 1;
    int temp = N;
    while(temp > 0){
        fact *= temp;
        temp -= 1; 
    }
    uartInit(); // Initialize UART
    printfNexys("Factorial of %d: %d ", N, fact);
}

Using PlatformIO, the bitstream is uploaded successfully on the board.
![image](https://user-images.githubusercontent.com/89577295/134098341-a990d4c8-2074-4738-a633-7ebc0b6b240b.png)

After clicking on “Run Debug”, the compilation is also done successfully.
![image](https://user-images.githubusercontent.com/89577295/134098356-ffe13899-eaf1-467f-9eeb-e8d2ab9aae23.png)

But the debug console fails with the following errors:
![image](https://user-images.githubusercontent.com/89577295/134098380-da61cf50-dd78-4dd0-877d-0e6ff1a76d7d.png)

My current driver used is: libwdi
![image](https://user-images.githubusercontent.com/89577295/134098396-b12bea55-22be-4f4f-a78f-864403c0ebdc.png)

I have installed in using Zadig and have also tried reinstalling the driver but the same issue persists.
![image](https://user-images.githubusercontent.com/89577295/134098417-b7cac68a-a002-4180-8e0c-fadfd78d8c0b.png)

I’m using Windows 10. Kindly help me resolve this issue.

**Comment by valeros** [comment]
Hi @vincentabraham ! The installed driver seems fine, but I don't see any debug modules (e.g. JTAG based) implemented or even mentioned in the https://github.com/Digilent/Nexys-A7-50T-OOB repository. It means you won't be able to debug you application using the design from that repository.

**Comment by vincentabraham** [comment]
Is there a way with which I could get the bitstream file including all the debug modules? I could only seem to find this one source containing the bitstream file and I don't have enough knowledge to create the file from scratch. Hoping if you could help me with this as I desperately need to get the FPGA running in order to start my project.

**Comment by valeros** [comment]
@vincentabraham 

> Is there a way with which I could get the bitstream file including all the debug modules?

As I already answered in #6, there is no such way. If you want to use the design from the https://github.com/Digilent/Nexys-A7-50T-OOB repository, then you need to implement it by yourself. Alternatively, you can use pregenerated bitstream based on the SweRVolf core. Here is an example https://github.com/platformio/platform-chipsalliance/tree/develop/examples/native-bare_c

And just to wrap up, this repository is not the right place to ask such general questions.
