### ISSUE TITLE
Error in Debugging the Nexys A7 50T

### ISSUE THREAD

**Issue by vincentabraham** [platformio/platform-chipsalliance#6]
Hi @vincentabraham ! The installed driver seems fine, but I don't see any debug modules (e.g. JTAG based) implemented or even mentioned in the https://github.com/Digilent/Nexys-A7-50T-OOB repository. It means you won't be able to debug you application using the design from that repository.

_Originally posted by @valeros in https://github.com/platformio/platform-chipsalliance/issues/5#issuecomment-923900668_

**Comment by vincentabraham** [comment]
Is there a way with which I could get the bitstream file including all the debug modules? I could only seem to find this one source containing the bitstream file and I don't have enough knowledge to create the file from scratch. Hoping if you could help me with this as I desperately need to get the FPGA running in order to start my project.

**Comment by valeros** [comment]
@vincentabraham Please don't open new issues, you could answer in the previous topic #5.

**Comment by valeros** [comment]
Duplicate #5
